# wrangler.toml
# Cloudflare Workers 配置文件

name = "fortune-telling-agent"
main = "src/index.ts"
compatibility_date = "2024-08-14"
compatibility_flags = ["streams_enable_constructors"]

[env.production]
name = "fortune-telling-agent-prod"

[env.staging]
name = "fortune-telling-agent-staging"

# 环境变量
[vars]
NODE_ENV = "production"

# 针对流式响应的特殊配置
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# KV 存储配置（如果需要）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"